"""first database revision

Revision ID: b37e86d5acf7
Revises: 
Create Date: 2023-11-13 19:16:00.056199

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from databricks.sqlalchemy import TIMESTAMP

# revision identifiers, used by Alembic.
revision: str = "b37e86d5acf7"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "test_model",
        sa.Column("bigint_col", sa.BigInteger(), primary_key=True),
        sa.Column("string_col", sa.String()),
        sa.Column("tinyint_col", sa.SmallInteger()),
        sa.Column("int_col", sa.Integer()),
        sa.Column("numeric_col", sa.Numeric(10, 2)),
        sa.Column("boolean_col", sa.Boolean()),
        sa.Column("date_col", sa.Date()),
        sa.Column("datetime_col", TIMESTAMP()),
        sa.Column("datetime_col_ntz", sa.DateTime()),
        sa.Column("time_col", sa.Time()),
        sa.Column("uuid_col", sa.Uuid()),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("test_model")
    # ### end Alembic commands ###
